### PR TITLE
Added reddit.com

### PR DESCRIPTION
**Pull request by f-breidenstein**

### CODE REVIEW

**Comment by andir** [comment]
please link license of the image

**Comment by andir** [comment]
Can we expect an update anytime soon?

**Comment by f-breidenstein** [comment]
Just wrote an email, asking reddit for the logo permission

**Comment by andir** [comment]
Any update?

**Comment by f-breidenstein** [comment]
I don't think that they will still respond to my request.

**Comment by andir** [comment]
rebase it and I'll sleep about it :-)

**Comment by andir** [comment]
ping?

**Pull request closed without merging**
